name: static analysis
on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']

    name: Static Analysis on PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Tools Cache
        uses: actions/cache@v5
        with:
          path: .cache/phpstan
          key: ${{ matrix.php }}-tools-${{ github.sha }}
          restore-keys: ${{ matrix.php }}-tools-

      - name: Run PHPStan
        run: composer static-analysis
